services:
  postgres:
    image: postgres:16
    container_name: ewallet_db
    environment:
      POSTGRES_USER: ewallet
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ewallet
    ports:
      - "5432:5432"
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: